### ISSUE TITLE
waifu2x bug

### ISSUE THREAD

**Issue by Shad0w1and** [WolframRhodium/Super-Resolution-Zoo#8]
using kice's VapourSynth plugin, the edge is broken at many places. [http://puu.sh/Di5wy/7a6f011f80.jpg](http://puu.sh/Di5wy/7a6f011f80.jpg) [http://puu.sh/Di5zC/7fbcf2c16c.jpg](http://puu.sh/Di5zC/7fbcf2c16c.jpg)
the old models from around October do not have this issue. But the old ones requires adding paddings for scaling. The new waifu2x models (lltcggie) do not require paddings for scaling but they are all having broken edges.

**Comment by WolframRhodium** [comment]
Hi, 
if the total memory capacity of your graphics card is large enough, you can increase parameters `patch_w` and `patch_w` of `core.mx.Predict`. 

Otherwise... please check [this](https://github.com/WolframRhodium/muvsfunc/blob/97125d2ccbcdcaa139d021381a89ed0c4d13447d/Collections/examples/super_resolution_mxnet.vpy#L30-L55) example for overlapping upscaling. Kice seems busy now.
